# Generated by Django 5.2.17 on 2026-09-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist_name', models.CharField(default='Manish', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('focus', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='sketches/')),
                ('score', models.DecimalField(decimal_places=1, default=8.5, max_digits=3)),
                ('strengths', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
