# Generated by Django 5.2.17 on 2026-09-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='ai_powered',
            field=models.BooleanField(default=False),
        ),
    ]
